//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenForum.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenForum.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INSERT OpenForum_Post VALUES(&apos;Mr_Question&apos;,	&apos;6/26/2009 12:00:00 AM&apos;,	&apos;Mr_Answer&apos;,	&apos;6/26/2009 7:00:00 PM&apos;,	&apos;What is OpenForum?&apos;, &apos;What is OpenForum? Who was it created by? Where can I learn more about it?&apos;,	1);
        ///INSERT OpenForum_Reply VALUES(@@Identity,	&apos;Mr_Answer&apos;,	&apos;6/26/2009 7:00:00 PM&apos;,	&apos;OpenForum is a free forum that plugs into any .Net MVC application. It was developed by Eric Herbrandson (http://software.herbrandson.com).
        ///You can view a quick tutorial on setting up OpenForum at the following url
        ///ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultData {
            get {
                return ResourceManager.GetString("DefaultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NicEdit - Micro Inline WYSIWYG
        ///* Copyright 2007-2008 Brian Kirchoff
        ///*
        ///* NicEdit is distributed under the terms of the MIT license
        ///* For more information visit http://nicedit.com/
        ///* Do not remove this copyright message
        ///*/
        ///var bkExtend = function() {
        ///    var args = arguments;
        ///    if (args.length == 1) args = [this, args[0]];
        ///    for (var prop in args[1]) args[0][prop] = args[1][prop];
        ///    return args[0];
        ///};
        ///function bkClass() { }
        ///bkClass.prototype.construct = function() { };
        ///bkClass.extend = funct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nicEdit {
            get {
                return ResourceManager.GetString("nicEdit", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap nicEditorIcons {
            get {
                object obj = ResourceManager.GetObject("nicEditorIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
