//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenForum.Core.Views.Forum
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using OpenForum.Core;
    using OpenForum.Core.Models;
    using OpenForum.Core.Views;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Forum/Index.cshtml")]
    public class _Page_Views_Forum_Index_cshtml : System.Web.Mvc.WebViewPage<OpenForum.Core.ViewModels.Interfaces.IIndexViewModel>
    {
#line hidden

        public _Page_Views_Forum_Index_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("           \r\n<div class=\"openforum_container\">\r\n\r\n    ");


Write(Model.IncludeDefaultStyles ? Html.Raw(ForumViewHelper.GetDefaultStyles()) : MvcHtmlString.Empty);

WriteLiteral("\r\n    ");


Write(Model.IncludeValidationSummary ? Html.ValidationSummary() : MvcHtmlString.Empty);

WriteLiteral("\r\n\r\n    <div class=\"openforum_actions\">\r\n        ");


   Write(Html.ActionLink("Write A New Post", "Post"));

WriteLiteral("\r\n    </div>\r\n    <div class=\"openforum_search\">\r\n");


         using (Html.BeginForm())
        {

WriteLiteral("            ");

WriteLiteral("Search:");

WriteLiteral(" ");


                                 
                            Write(Html.TextBox("searchQuery"));


WriteLiteral(" <input type=\"submit\" value=\"go\" />\r\n");


        }

WriteLiteral("    </div>\r\n    <div class=\"openforum_message\">");


                              Write(Model.Message);

WriteLiteral("</div>\r\n    <div class=\"openforum_maincontent\">\r\n");


         foreach (var item in Model.Posts ?? new Post[0])
        {
        

WriteLiteral("            <div class=\"openforum_item\">\r\n                <div class=\"openforum_s" +
"tats\">\r\n                    <div>\r\n                        <div>");


                        Write(item.LastPostDate.ToString("M/d/yy"));

WriteLiteral("</div>\r\n                        <div>");


                        Write(item.LastPostDate.ToString("h:mm tt"));

WriteLiteral("</div>\r\n                    </div>\r\n                    <div>\r\n                  " +
"      <div>");


                        Write(item.ViewCount);

WriteLiteral(" Views</div>\r\n                        <div>");


                        Write(item.Replies.Count);

WriteLiteral(" Posts</div>\r\n                    </div>\r\n                </div>\r\n               " +
" <div>\r\n                    <h2 class=\"openforum_title\">\r\n                      " +
"  ");


                   Write(Html.ActionLink(item.Title, "view", new { id = item.Id, title = ForumViewHelper.ToUrlFriendlyTitle(item.Title) }));

WriteLiteral("\r\n                    </h2>\r\n                </div>\r\n                <div class=\"" +
"openforum_postpreview\">\r\n                    Original post: ");


                              Write(item.CreatedBy.Username);

WriteLiteral(" wrote - ");


                                                               Write(Html.Raw(item.Body.RemoveAllMarkup().WithMaxLength(200)));

WriteLiteral("\r\n                </div>\r\n\r\n");


                 if (item.Replies.Count > 0)
                { 

WriteLiteral("                    <div class=\"openforum_postpreview\">\r\n                        " +
"Latest post: ");


                                Write(item.LastPostBy.Username);

WriteLiteral(" wrote - ");


                                                                  Write(Html.Raw(item.GetLatestResponse().RemoveAllMarkup().WithMaxLength(200)));

WriteLiteral("\r\n                    </div>\r\n");


                }

WriteLiteral("                \r\n                <span></span>\r\n            </div>\r\n");


        

WriteLiteral("            <div class=\"openforum_clear\">\r\n            </div>\r\n");


        
        }

WriteLiteral("    </div>\r\n    <div class=\"openforum_index_paging\">\r\n");


         if ((Model.Posts ?? new Post[0]).Count() > 0)
        {

WriteLiteral("            <span>Page ");


                   Write(Model.CurrentPage + 1);

WriteLiteral(" of ");


                                              Write(Model.TotalPages);

WriteLiteral("</span>\r\n");


        }

WriteLiteral("        \r\n");


         if (Model.CurrentPage > 0)
        {
            using (Html.BeginForm())
            {

WriteLiteral("            <input type=\"submit\" value=\"&lt;&lt;&lt;\" />\r\n");



WriteLiteral("            <input type=\"hidden\" name=\"searchQuery\" value=\"");


                                                      Write(Model.SearchQuery);

WriteLiteral("\" />\r\n");



WriteLiteral("            <input type=\"hidden\" name=\"page\" value=\"");


                                                Write(Model.CurrentPage - 1);

WriteLiteral("\" />\r\n");


            }
        }

WriteLiteral("        \r\n");


         if (Model.CurrentPage < Model.TotalPages - 1)
        {
            using (Html.BeginForm())
            {

WriteLiteral("            <input type=\"submit\" value=\"&gt;&gt;&gt;\" />\r\n");



WriteLiteral("            <input type=\"hidden\" name=\"searchQuery\" value=\"");


                                                      Write(Model.SearchQuery);

WriteLiteral("\" />\r\n");



WriteLiteral("            <input type=\"hidden\" name=\"page\" value=\"");


                                                Write(Model.CurrentPage + 1);

WriteLiteral("\" />\r\n");


            }
        }

WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
