//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenForum.Core.Views.Forum
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using OpenForum.Core.Views;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Forum/View.cshtml")]
    public class _Page_Views_Forum_View_cshtml : System.Web.Mvc.WebViewPage<OpenForum.Core.ViewModels.Interfaces.IViewViewModel>
    {
#line hidden

        public _Page_Views_Forum_View_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


WriteLiteral("\r\n<div class=\"openforum_container\">\r\n    \r\n    ");


Write(Model.IncludeDefaultStyles ? Html.Raw(ForumViewHelper.GetDefaultStyles()) : MvcHtmlString.Empty);

WriteLiteral("\r\n    ");


Write(Model.IncludeValidationSummary ? Html.ValidationSummary() : MvcHtmlString.Empty);

WriteLiteral("\r\n    \r\n    <div class=\"openforum_title\">");


                            Write(Model.Post.Title);

WriteLiteral("</div>\r\n\r\n    <table class=\"openforum_maincontent\">\r\n        <tr>\r\n            <t" +
"d class=\"openforum_body\">");


                                  Write(Html.Raw(Model.Post.Body));

WriteLiteral("</td>\r\n\r\n");


             if (Model.Post.CreatedBy.HasImageUrl)
            {

WriteLiteral("            <td class=\"openforum_user_image\">\r\n                <div><img src=\"");


                          Write(Model.Post.CreatedBy.ImageUrl);

WriteLiteral("\" alt=\"");


                                                               Write(Model.Post.CreatedBy.Username);

WriteLiteral("\" /></div>\r\n            </td>\r\n");


            }

WriteLiteral("\r\n            <td class=\"openforum_user\">\r\n                <div>                \r" +
"\n");


                     if (Model.Post.CreatedBy.HasUserUrl) 
                    {

WriteLiteral("                        <a href=\"");


                            Write(Model.Post.CreatedBy.UserUrl);

WriteLiteral("\">");


                                                           Write(Model.Post.CreatedBy.Username);

WriteLiteral("</a>\r\n");


                    } 
                    else 
                    {
                        
                   Write(Model.Post.CreatedBy.Username);

                                                      
                    }

WriteLiteral("                </div>\r\n                \r\n                <div>");


                Write(Model.Post.CreatedDate.ToString("MM/dd/yyyy HH:mm tt"));

WriteLiteral("</div>\r\n\r\n                ");


            Write(Model.CurrentUser != null && Model.Post.CreatedById == Model.CurrentUser.Id ? Html.ActionLink("Edit", "Post", new { id = Model.Post.Id }) : MvcHtmlString.Empty);

WriteLiteral("\r\n\r\n            </td>\r\n        </tr>\r\n\r\n");


         foreach (var item in Model.Post.Replies)
        {
            

WriteLiteral("        <tr>\r\n            <td class=\"openforum_body\">");


                                  Write(Html.Raw(item.Body));

WriteLiteral("</td>\r\n\r\n");


             if (item.CreatedBy.HasImageUrl) 
            { 

WriteLiteral("            <td class=\"openforum_user_image\">\r\n                <div><img src=\"");


                          Write(item.CreatedBy.ImageUrl);

WriteLiteral("\" alt=\"");


                                                         Write(item.CreatedBy.Username);

WriteLiteral("\" /></div>\r\n            </td>\r\n");


            }

WriteLiteral("\r\n            <td class=\"openforum_user\">\r\n                <div>\r\n               " +
" \r\n");


                     if (item.CreatedBy.HasUserUrl)
                    { 

WriteLiteral("                        <a href=\"");


                            Write(item.CreatedBy.UserUrl);

WriteLiteral(" %>\">");


                                                        Write(item.CreatedBy.Username);

WriteLiteral("</a>\r\n");


                    }
                    else
                    {
                        
                   Write(item.CreatedBy.Username);

                                                
                    }

WriteLiteral("                \r\n                </div>\r\n                \r\n                <div>" +
"");


                Write(item.CreatedDate.ToString("MM/dd/yyyy HH:mm tt"));

WriteLiteral("</div>\r\n\r\n                ");


            Write(Model.CurrentUser != null && item.CreatedById == Model.CurrentUser.Id ? Html.ActionLink("Edit", "Reply", new { id = item.Id, postId = Model.Post.Id }) : MvcHtmlString.Empty);

WriteLiteral("\r\n\r\n            </td>\r\n        </tr>\r\n");


            
        }

WriteLiteral("\r\n    </table>\r\n\r\n    <div class=\"openforum_actions\">\r\n        ");


   Write(Html.ActionLink("Back", "index"));

WriteLiteral("\r\n        ");


   Write(Html.ActionLink("Reply", "Reply", new { id = "", postId = Model.Post.Id, title = ForumViewHelper.ToUrlFriendlyTitle(Model.Post.Title) }));

WriteLiteral("\r\n    </div>\r\n</div>\r\n");


        }
    }
}
